{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Air Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "adc_value{sensor=\"MQ-2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Quality (1m Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(adc_value{sensor=\"MQ-2\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Quality (5m Average)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(adc_value{sensor=\"MQ-2\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}